//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.App.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add project.
        /// </summary>
        public static string AddProject {
            get {
                return ResourceManager.GetString("AddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architectural Diagrams.
        /// </summary>
        public static string ArchitecturalDiagrams {
            get {
                return ResourceManager.GetString("ArchitecturalDiagrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building License Attachment.
        /// </summary>
        public static string BuildingLicenseAttachment {
            get {
                return ResourceManager.GetString("BuildingLicenseAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building License Number.
        /// </summary>
        public static string BuildingLicenseNumber {
            get {
                return ResourceManager.GetString("BuildingLicenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Technique.
        /// </summary>
        public static string BuildingTechnique {
            get {
                return ResourceManager.GetString("BuildingTechnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction Diagrams.
        /// </summary>
        public static string ConstructionDiagrams {
            get {
                return ResourceManager.GetString("ConstructionDiagrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulting Office Name.
        /// </summary>
        public static string ConsultingOfficeName {
            get {
                return ResourceManager.GetString("ConsultingOfficeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor Name.
        /// </summary>
        public static string ContractorName {
            get {
                return ResourceManager.GetString("ContractorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Project.
        /// </summary>
        public static string DeleteProject {
            get {
                return ResourceManager.GetString("DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Project.
        /// </summary>
        public static string EditProject {
            get {
                return ResourceManager.GetString("EditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elictrical Diagrams.
        /// </summary>
        public static string ElictricalDiagrams {
            get {
                return ResourceManager.GetString("ElictricalDiagrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Cost.
        /// </summary>
        public static string EstimatedCost {
            get {
                return ResourceManager.GetString("EstimatedCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floors Number.
        /// </summary>
        public static string FloorsNumber {
            get {
                return ResourceManager.GetString("FloorsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument Attachment.
        /// </summary>
        public static string InstrumentAttachment {
            get {
                return ResourceManager.GetString("InstrumentAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument Number.
        /// </summary>
        public static string InstrumentNumber {
            get {
                return ResourceManager.GetString("InstrumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanical Diagrams.
        /// </summary>
        public static string MechanicalDiagrams {
            get {
                return ResourceManager.GetString("MechanicalDiagrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Arabic.
        /// </summary>
        public static string NameArabic {
            get {
                return ResourceManager.GetString("NameArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name English.
        /// </summary>
        public static string NameEnglish {
            get {
                return ResourceManager.GetString("NameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Details.
        /// </summary>
        public static string ProjectDetails {
            get {
                return ResourceManager.GetString("ProjectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects Managment.
        /// </summary>
        public static string ProjectsManagment {
            get {
                return ResourceManager.GetString("ProjectsManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Type.
        /// </summary>
        public static string ProjectTypeId {
            get {
                return ResourceManager.GetString("ProjectTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Full Address.
        /// </summary>
        public static string PropertyFullAddress {
            get {
                return ResourceManager.GetString("PropertyFullAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Latitude.
        /// </summary>
        public static string PropertyLatitude {
            get {
                return ResourceManager.GetString("PropertyLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Longitude.
        /// </summary>
        public static string PropertyLongitude {
            get {
                return ResourceManager.GetString("PropertyLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Number.
        /// </summary>
        public static string PropertyNumber {
            get {
                return ResourceManager.GetString("PropertyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter Name.
        /// </summary>
        public static string QuarterName {
            get {
                return ResourceManager.GetString("QuarterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil Report.
        /// </summary>
        public static string SoilReport {
            get {
                return ResourceManager.GetString("SoilReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Area.
        /// </summary>
        public static string TotalArea {
            get {
                return ResourceManager.GetString("TotalArea", resourceCulture);
            }
        }
    }
}
